services:
  postgres:
    image: postgres:16
    container_name: mtech-postgres
    environment:
      POSTGRES_DB: mtech_security
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  aapi:
    build: .
    container_name: mtech-security-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mtech_security
    depends_on:
      - postgres

volumes:
  postgres_data: