spring.application.name=security

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/security
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true

#JWT
jwt.secret=uma-chave-secreta-muito-longa-e-segura-para-o-mtech-security-jwt-2026